"""empty message

Revision ID: 23216669d282
Revises: 19318205eda6
Create Date: 2017-02-26 14:10:23.897602

"""

# revision identifiers, used by Alembic.
revision = '23216669d282'
down_revision = '19318205eda6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
